// <auto-generated />
using System;
using System.Collections.Generic;

namespace CADL.SosDsl {

    /// <summary>
    /// Generated contract instances implement this interface so the
    /// runtime can drive them without knowing about specific contract
    /// types. One concrete class per CADL contract is emitted into
    /// the Generated/ directory.
    /// </summary>
    public interface IContractInstance {
        string ContractId { get; }
        string InstanceId { get; }
        bool Closed { get; }
        void HandleEvent(in PortEvent ev, ContractRuntime rt);
        void Tick(long nowMs, ContractRuntime rt);
        IDictionary<string, object> WorldSnapshot();
    }

    /// <summary>
    /// In-process orchestrator. Owns the instances, the event bus
    /// channels for lifecycle and violation events, and the world
    /// snapshot. Time is supplied by the host (Unity's
    /// MonoBehaviour.Update -> rt.Tick(simNowMs)).
    /// </summary>
    public sealed class ContractRuntime {
        private readonly Dictionary<string, IContractInstance> _instances =
            new Dictionary<string, IContractInstance>();
        private readonly Dictionary<string, object> _world =
            new Dictionary<string, object>();

        public readonly EventBus<ContractEvent> Events = new EventBus<ContractEvent>();

        public IReadOnlyDictionary<string, object> World => _world;
        public IEnumerable<IContractInstance> Instances => _instances.Values;

        public void Register(IContractInstance inst) {
            if (inst == null) throw new ArgumentNullException(nameof(inst));
            _instances[inst.InstanceId] = inst;
        }

        public bool TryGet<T>(string instanceId, out T inst)
            where T : class, IContractInstance {
            if (_instances.TryGetValue(instanceId, out var v) && v is T t) {
                inst = t; return true;
            }
            inst = null; return false;
        }

        public void UpdateWorld(IDictionary<string, object> snapshot) {
            if (snapshot == null) return;
            foreach (var kv in snapshot) _world[kv.Key] = kv.Value;
        }

        public void PostEvent(string name, long tMs,
                              IDictionary<string, object> payload = null) {
            var ev = new PortEvent { Name = name, TMs = tMs, Payload = AsRO(payload) };
            foreach (var inst in _instances.Values) {
                if (inst.Closed) continue;
                inst.HandleEvent(ev, this);
            }
        }

        public void Tick(long nowMs) {
            foreach (var inst in _instances.Values) {
                if (inst.Closed) continue;
                inst.Tick(nowMs, this);
            }
        }

        public void Emit(in ContractEvent ev) => Events.Post(ev);

        public IDictionary<string, object> SnapshotFor(IContractInstance inst) {
            var snap = new Dictionary<string, object>(_world);
            var perInst = inst.WorldSnapshot();
            if (perInst != null) {
                foreach (var kv in perInst) snap[kv.Key] = kv.Value;
            }
            snap["contract_id"] = inst.ContractId;
            snap["instance_id"] = inst.InstanceId;
            return snap;
        }

        private static IReadOnlyDictionary<string, object> AsRO(IDictionary<string, object> d) {
            return d == null ? null : new Dictionary<string, object>(d);
        }
    }
}
