// <auto-generated />
using System;
using System.Collections.Generic;

namespace CADL.SosDsl {

    public enum ContractEventKind {
        Lifecycle,
        Violation,
    }

    /// <summary>
    /// Discrete event posted into the runtime's EventBus, or emitted
    /// on lifecycle transitions and violations. Mirrors the Python
    /// reference runtime's NDJSON record shape.
    /// </summary>
    [Serializable]
    public struct ContractEvent {
        public ContractEventKind Kind;
        public string ContractId;
        public string InstanceId;
        public string TransitionId;
        public string FromState;
        public string ToState;
        public string Norm;
        public Severity Severity;
        public long TMs;
        public string Cause;        // "open" | "event" | "deadline" | "monitor" | "jump"
        public string DetectedBy;   // "deadline:<id>" | "monitor:<id>"
        public IReadOnlyDictionary<string, object> Payload;

        public override string ToString() {
            if (Kind == ContractEventKind.Lifecycle) {
                return $"[lifecycle {ContractId}/{InstanceId} {FromState} -> {ToState} ({TransitionId}, {Cause}) @ {TMs}ms]";
            } else {
                return $"[violation {ContractId}/{InstanceId} {Norm} {Severity} {DetectedBy} @ {TMs}ms]";
            }
        }
    }

    /// <summary>External event posted to the runtime (port message).</summary>
    public struct PortEvent {
        public string Name;
        public long TMs;
        public IReadOnlyDictionary<string, object> Payload;
    }
}
