// <auto-generated />
using System;
using System.Collections.Generic;

namespace CADL.SosDsl {

    /// <summary>
    /// In-process synchronous event bus. Subscribers are invoked in
    /// FIFO subscription order. Used internally by ContractRuntime.
    /// </summary>
    public sealed class EventBus<T> {
        private readonly List<Action<T>> _subscribers = new List<Action<T>>();

        public void Subscribe(Action<T> handler) {
            if (handler != null) _subscribers.Add(handler);
        }

        public void Post(T evt) {
            // Snapshot to allow re-entrant Subscribe.
            var snap = _subscribers.ToArray();
            foreach (var s in snap) {
                try { s(evt); }
                catch (Exception ex) {
                    System.Diagnostics.Debug.WriteLine(
                        $"EventBus subscriber threw: {ex}");
                }
            }
        }
    }
}
