// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace CADL.SosDsl {

    /// <summary>
    /// Minimal CADL predicate evaluator, kept deliberately small to
    /// match the v0.1 SoS-DSL examples. Supports: numeric literals,
    /// double-quoted strings, bare identifiers (enum-like literals
    /// when unresolved), dotted member access, list literals
    /// ([a, b, c]), the comparison operators &lt;, &lt;=, &gt;, &gt;=,
    /// ==, !=, the logical operators AND, OR, NOT, and the IN
    /// operator. Function calls are not supported and cause the whole
    /// expression to evaluate to false.
    /// </summary>
    public static class PredicateEvaluator {
        private static readonly Regex _stripIndex =
            new Regex(@"\[[^\]]*\]", RegexOptions.Compiled);

        public static bool Evaluate(string expr, IDictionary<string, object> world) {
            if (string.IsNullOrEmpty(expr)) return false;
            try {
                var toks = Tokenize(expr);
                if (toks.Count == 0) return false;
                int i = 0;
                var v = EvalOr(toks, ref i, world);
                return AsBool(v);
            } catch (Exception) {
                return false;
            }
        }

        // --- token kinds ---
        private enum Tk { Num, Str, Op, Kw, LB, RB, LP, RP, Co, Id }

        private struct Token {
            public Tk Kind;
            public string Value;
            public Token(Tk k, string v) { Kind = k; Value = v; }
        }

        private static readonly Regex _tokenRe = new Regex(
            @"\s*(?:" +
            @"(?<NUM>\d+(?:\.\d+)?)" +
            @"|(?<STR>""[^""]*"")" +
            @"|(?<OP><=|>=|==|!=|<|>)" +
            @"|(?<KW>AND|OR|NOT|IN|in)" +
            @"|(?<LB>\[)|(?<RB>\])|(?<LP>\()|(?<RP>\))" +
            @"|(?<CO>,)" +
            @"|(?<ID>[A-Za-z_][A-Za-z_0-9]*(?:\.[A-Za-z_][A-Za-z_0-9]*)*" +
            @"(?:\[[^\]]*\])?(?:\.[A-Za-z_][A-Za-z_0-9]*)*)" +
            @")",
            RegexOptions.Compiled);

        private static List<Token> Tokenize(string expr) {
            var result = new List<Token>();
            int pos = 0;
            while (pos < expr.Length) {
                var m = _tokenRe.Match(expr, pos);
                if (!m.Success || m.Index != pos) {
                    if (char.IsWhiteSpace(expr[pos])) { pos++; continue; }
                    throw new Exception($"unexpected token at {pos}");
                }
                if (m.Groups["NUM"].Success) result.Add(new Token(Tk.Num, m.Groups["NUM"].Value));
                else if (m.Groups["STR"].Success) result.Add(new Token(Tk.Str, m.Groups["STR"].Value));
                else if (m.Groups["OP"].Success)  result.Add(new Token(Tk.Op,  m.Groups["OP"].Value));
                else if (m.Groups["KW"].Success)  result.Add(new Token(Tk.Kw,  m.Groups["KW"].Value));
                else if (m.Groups["LB"].Success)  result.Add(new Token(Tk.LB,  "["));
                else if (m.Groups["RB"].Success)  result.Add(new Token(Tk.RB,  "]"));
                else if (m.Groups["LP"].Success)  result.Add(new Token(Tk.LP,  "("));
                else if (m.Groups["RP"].Success)  result.Add(new Token(Tk.RP,  ")"));
                else if (m.Groups["CO"].Success)  result.Add(new Token(Tk.Co,  ","));
                else if (m.Groups["ID"].Success)  result.Add(new Token(Tk.Id,  m.Groups["ID"].Value));
                else throw new Exception("internal tokenizer error");
                pos = m.Index + m.Length;
            }
            return result;
        }

        // --- name resolution: dotted -> walk dict; unresolved bare id -> enum-literal ---
        private static object Resolve(string name, IDictionary<string, object> world) {
            string bare = _stripIndex.Replace(name, string.Empty);
            var parts = bare.Split('.');
            object cur = world;
            foreach (var p in parts) {
                if (cur is IDictionary<string, object> d) {
                    if (d.TryGetValue(p, out var v)) cur = v;
                    else { cur = null; goto unresolved; }
                } else {
                    cur = null; goto unresolved;
                }
            }
            return cur;
            unresolved:
            return parts.Length == 1 ? (object)parts[0] : null;
        }

        private static object EvalAtom(Token t, IDictionary<string, object> world) {
            switch (t.Kind) {
                case Tk.Num:
                    if (t.Value.Contains('.')) return double.Parse(t.Value,
                        System.Globalization.CultureInfo.InvariantCulture);
                    return long.Parse(t.Value);
                case Tk.Str:
                    return t.Value.Substring(1, t.Value.Length - 2);
                case Tk.Id:
                    if (t.Value == "true") return true;
                    if (t.Value == "false") return false;
                    return Resolve(t.Value, world);
                default:
                    throw new Exception("unexpected atom");
            }
        }

        private static object EvalValue(List<Token> toks, ref int i,
                                        IDictionary<string, object> world) {
            if (i >= toks.Count) throw new Exception("end of expression");
            var t = toks[i];
            if (t.Kind == Tk.LB) {
                var items = new List<object>();
                i++;
                while (i < toks.Count && toks[i].Kind != Tk.RB) {
                    items.Add(EvalValue(toks, ref i, world));
                    if (i < toks.Count && toks[i].Kind == Tk.Co) i++;
                }
                if (i >= toks.Count) throw new Exception("unterminated list");
                i++;
                return items;
            }
            if (t.Kind == Tk.LP) {
                i++;
                var v = EvalOr(toks, ref i, world);
                if (i >= toks.Count || toks[i].Kind != Tk.RP)
                    throw new Exception("missing ')'");
                i++;
                return v;
            }
            // Reject ID followed by LP (function call) — fail-safe to false.
            if (t.Kind == Tk.Id && i + 1 < toks.Count && toks[i + 1].Kind == Tk.LP) {
                throw new Exception($"function calls unsupported: {t.Value}(...)");
            }
            i++;
            return EvalAtom(t, world);
        }

        private static object EvalComparison(List<Token> toks, ref int i,
                                             IDictionary<string, object> world) {
            var lhs = EvalValue(toks, ref i, world);
            if (i < toks.Count) {
                var t = toks[i];
                if (t.Kind == Tk.Op) {
                    string op = t.Value; i++;
                    var rhs = EvalValue(toks, ref i, world);
                    return Compare(op, lhs, rhs);
                }
                if (t.Kind == Tk.Kw && t.Value.ToUpperInvariant() == "IN") {
                    i++;
                    var rhs = EvalValue(toks, ref i, world);
                    if (rhs is IList list) {
                        foreach (var el in list) if (object.Equals(el, lhs)) return true;
                        return false;
                    }
                    return false;
                }
            }
            return lhs;
        }

        private static object EvalUnary(List<Token> toks, ref int i,
                                        IDictionary<string, object> world) {
            if (i < toks.Count && toks[i].Kind == Tk.Kw && toks[i].Value == "NOT") {
                i++;
                var v = EvalUnary(toks, ref i, world);
                return !AsBool(v);
            }
            return EvalComparison(toks, ref i, world);
        }

        private static object EvalAnd(List<Token> toks, ref int i,
                                      IDictionary<string, object> world) {
            var lhs = EvalUnary(toks, ref i, world);
            while (i < toks.Count && toks[i].Kind == Tk.Kw && toks[i].Value == "AND") {
                i++;
                var rhs = EvalUnary(toks, ref i, world);
                lhs = AsBool(lhs) && AsBool(rhs);
            }
            return lhs;
        }

        private static object EvalOr(List<Token> toks, ref int i,
                                     IDictionary<string, object> world) {
            var lhs = EvalAnd(toks, ref i, world);
            while (i < toks.Count && toks[i].Kind == Tk.Kw && toks[i].Value == "OR") {
                i++;
                var rhs = EvalAnd(toks, ref i, world);
                lhs = AsBool(lhs) || AsBool(rhs);
            }
            return lhs;
        }

        // --- helpers ---
        private static bool AsBool(object v) {
            if (v is bool b) return b;
            if (v == null) return false;
            if (v is string s) return !string.IsNullOrEmpty(s);
            if (v is long l)   return l != 0;
            if (v is int i32)  return i32 != 0;
            if (v is double d) return d != 0;
            return true;
        }

        private static double AsNum(object v) {
            if (v is long l)   return (double)l;
            if (v is int i32)  return (double)i32;
            if (v is double d) return d;
            if (v is string s &&
                double.TryParse(s,
                    System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture,
                    out var p)) return p;
            return double.NaN;
        }

        private static bool Compare(string op, object lhs, object rhs) {
            switch (op) {
                case "==": return object.Equals(NormalizeForEq(lhs),
                                                NormalizeForEq(rhs));
                case "!=": return !object.Equals(NormalizeForEq(lhs),
                                                 NormalizeForEq(rhs));
            }
            double a = AsNum(lhs), b = AsNum(rhs);
            switch (op) {
                case "<":  return a < b;
                case "<=": return a <= b;
                case ">":  return a > b;
                case ">=": return a >= b;
            }
            return false;
        }

        private static object NormalizeForEq(object o) {
            if (o is long l)   return (double)l;
            if (o is int i32)  return (double)i32;
            return o;
        }
    }
}
