// <auto-edited-on-import="false">
//   Hand-written harness for the SoS-DSL contract runtime, *not*
//   regenerated by `cadl codegen`. Edit freely.
//
// Place a single GameObject in your scene with this component
// attached. It owns one ContractRuntime, registers one
// DeliverySlaContract instance, and exposes Inspector buttons /
// keys to drive it through the three demo scenarios.
//
// Scenarios match the Python reference runtime's demo_delivery.py:
//   - Happy   : assign  + ack within deadline  -> Accepted
//   - Late    : assign  + (no ack)             -> Violated  (deadline)
//   - Battery : assign  + battery drops < 20   -> Violated  (monitor)
// </auto-edited-on-import>
using System.Collections.Generic;
using UnityEngine;

namespace CADL.SosDsl.Demo {

    public sealed class DeliveryContractDemo : MonoBehaviour {

        [Header("Scenario (set in Inspector or change at runtime)")]
        public Scenario scenario = Scenario.Happy;

        [Header("World snapshot")]
        [Tooltip("Robot battery level (0..100). The battery_guard "
                 + "monitor fires when this drops below 20 in Assigned.")]
        [Range(0f, 100f)] public float robotBattery = 90f;

        [Header("Sim time control")]
        [Tooltip("If true, time advances with Unity's Time.time. "
                 + "If false, you can scrub manualSimTimeMs in the Inspector.")]
        public bool useUnityTime = true;
        public long manualSimTimeMs = 0L;

        public enum Scenario { Happy, Late, Battery }

        private ContractRuntime _rt;
        private DeliverySlaContract _instance;
        private long _startMs;
        private bool _assigned;
        private bool _ackPosted;
        private readonly List<ContractEvent> _trace = new List<ContractEvent>();

        private void Awake() {
            _rt = new ContractRuntime();
            _rt.Events.Subscribe(OnContractEvent);

            // Open one DELIVERY_SLA instance.
            _instance = new DeliverySlaContract(
                instanceId: "req-001", rt: _rt, nowMs: 0L);
            _rt.Register(_instance);

            // Seed world.
            _rt.UpdateWorld(new Dictionary<string, object> {
                { "ROBOT", new Dictionary<string, object> {
                    { "battery", (double)robotBattery },
                }},
            });
        }

        private void Update() {
            long nowMs = useUnityTime
                ? (long)(Time.time * 1000f)
                : manualSimTimeMs;

            // Stream the (possibly-changed) battery into the world.
            _rt.UpdateWorld(new Dictionary<string, object> {
                { "ROBOT", new Dictionary<string, object> {
                    { "battery", (double)robotBattery },
                }},
            });

            // Drive the scenario timeline.
            DriveScenario(nowMs);

            _rt.Tick(nowMs);
        }

        private void DriveScenario(long nowMs) {
            if (_instance.Closed) return;

            // 1) After 100 ms, post the assign event for all scenarios.
            if (!_assigned && nowMs >= 100) {
                _assigned = true;
                _rt.PostEvent(
                    "DISPATCHER -> ROBOT[i] : route_assignment",
                    nowMs);
            }

            // 2) For Happy only, post the ack within the deadline.
            if (scenario == Scenario.Happy && _assigned && !_ackPosted
                    && nowMs >= 200) {
                _ackPosted = true;
                _rt.PostEvent(
                    "ROBOT[i] -> DISPATCHER : ack(accepted)",
                    nowMs);
            }
            // 3) Late: do nothing — the 5s deadline lifts to Violated.
            // 4) Battery: drop battery below threshold while Assigned.
            if (scenario == Scenario.Battery && _assigned && nowMs >= 1000
                    && robotBattery >= 20f) {
                robotBattery = 10f;
            }
        }

        private void OnContractEvent(ContractEvent ev) {
            _trace.Add(ev);
            Debug.Log(ev.ToString());
        }

        // Inspector reset button replacement.
        [ContextMenu("Reset")]
        public void ResetScenario() {
            _trace.Clear();
            _assigned = false;
            _ackPosted = false;
            manualSimTimeMs = 0L;
            _startMs = 0L;
            // Re-seed runtime + instance.
            _rt = new ContractRuntime();
            _rt.Events.Subscribe(OnContractEvent);
            _instance = new DeliverySlaContract(
                instanceId: "req-001", rt: _rt, nowMs: 0L);
            _rt.Register(_instance);
        }

        public IReadOnlyList<ContractEvent> Trace => _trace;
        public string CurrentState =>
            _instance != null ? _instance.State.ToString() : "(none)";
    }
}
