"""End-to-end demo of the SoS-DSL contract runtime.

Drives one DELIVERY_SLA contract instance through three scenarios and
prints the resulting trace to stdout. Suitable as a smoke test and as
a starting point for arbitrator integration.

Usage
-----
    python -m cadl.runtime.demo_delivery
    python -m cadl.runtime.demo_delivery --scenario late
    python -m cadl.runtime.demo_delivery --scenario battery

The IR file is generated by:

    cadl sim-ir examples/sos_dsl_robot_delivery.cadl --format json \\
        > cadl/runtime/tests/fixture_delivery.ir.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .engine import ContractRuntime


FIXTURE = Path(__file__).parent / "tests" / "fixture_delivery.ir.json"


def scenario_happy(rt: ContractRuntime) -> None:
    rt.open_instance("DELIVERY_SLA", "req-001", t_ms=0)
    rt.update_world({"ROBOT": {"battery": 90}})
    rt.post_event("DISPATCHER -> ROBOT[i] : route_assignment", t_ms=100)
    rt.post_event("ROBOT[i] -> DISPATCHER : ack(accepted)", t_ms=200)
    rt.tick(now_ms=1_000)


def scenario_late(rt: ContractRuntime) -> None:
    """Robot never acks within the 5s deadline -> Violated."""
    rt.open_instance("DELIVERY_SLA", "req-late", t_ms=0)
    rt.update_world({"ROBOT": {"battery": 90}})
    rt.post_event("DISPATCHER -> ROBOT[i] : route_assignment", t_ms=100)
    # Tick past the 5s deadline without an ack.
    rt.tick(now_ms=6_500)


def scenario_battery(rt: ContractRuntime) -> None:
    """Battery drops below threshold while Assigned -> Violated."""
    rt.open_instance("DELIVERY_SLA", "req-batt", t_ms=0)
    rt.update_world({"ROBOT": {"battery": 50}})
    rt.post_event("DISPATCHER -> ROBOT[i] : route_assignment", t_ms=100)
    rt.tick(now_ms=600)
    rt.update_world({"ROBOT": {"battery": 10}})
    rt.tick(now_ms=1_200)


SCENARIOS = {
    "happy": scenario_happy,
    "late": scenario_late,
    "battery": scenario_battery,
}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--scenario", choices=list(SCENARIOS), default="happy")
    p.add_argument("--ir", type=Path, default=FIXTURE)
    p.add_argument("--log", type=Path, default=None,
                   help="optional NDJSON log path")
    args = p.parse_args()

    rt = ContractRuntime(args.ir, log_path=args.log)
    SCENARIOS[args.scenario](rt)

    print(f"# scenario: {args.scenario}")
    print(f"# events:   {len(rt.log)}")
    for r in rt.log:
        print(json.dumps(r, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
